
// HR OPERATIONS ===> FAMILY TYPES
export const GET_TRANSITION_FAMILY_DATA = "GET_TRANSITION_FAMILY_DATA";
export const GET_TRANSITION_FAMILY_START = "GET_TRANSITION_FAMILY_START";
export const GET_TRANSITION_FAMILY_DATA_SINGLE = "GET_TRANSITION_FAMILY_DATA_SINGLE";
export const GET_TRANSITION_FAMILY_END = "GET_TRANSITION_FAMILY_END";


// HR OPERATIONS ===> COST CENTER
export const GET_TRANSITION_COST_CENTRE_DATA = "GET_TRANSITION_COST_CENTRE_DATA";
export const GET_TRANSITION_COST_CENTRE_START = "GET_TRANSITION_COST_CENTRE_START";
export const GET_TRANSITION_COST_CENTRE_DATA_SINGLE = "GET_TRANSITION_COST_CENTRE_DATA_SINGLE";
export const GET_TRANSITION_COST_CENTRE_END = "GET_TRANSITION_COST_CENTRE_END";


// HR OPERATIONS ===> COUNTRY
export const GET_TRANSITION_COUNTRY_DATA = "GET_TRANSITION_COUNTRY_DATA";
export const GET_TRANSITION_COUNTRY_START = "GET_TRANSITION_COUNTRY_START";
export const GET_TRANSITION_COUNTRY_DATA_SINGLE = "GET_TRANSITION_COUNTRY_DATA_SINGLE";
export const GET_TRANSITION_COUNTRY_END = "GET_TRANSITION_COUNTRY_END";


// HR OPERATIONS ===> DEPARTMENT
export const GET_TRANSITION_DEPARTMENT_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DEPARTMENT_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DEPARTMENT_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DEPARTMENT_END = "GET_TRANSITION_DEPARTMENT_END";

// HR OPERATIONS ===> DESIGNATION
export const GET_TRANSITION_DESIGNATION_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DESIGNATION_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DESIGNATION_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DESIGNATION_END = "GET_TRANSITION_DEPARTMENT_END";

// HR OPERATIONS ===> BASE CITY
export const GET_TRANSITION_BASE_CITY_DATA = "GET_TRANSITION_BASE_CITY_DATA";
export const GET_TRANSITION_BASE_CITY_START = "GET_TRANSITION_BASE_CITY_START";
export const GET_TRANSITION_BASE_CITY_DATA_SINGLE = "GET_TRANSITION_BASE_CITY_DATA_SINGLE";
export const GET_TRANSITION_BASE_CITY_END = "GET_TRANSITION_BASE_CITY_END";

// HR OPERATIONS ===> DIVISIONS
export const GET_TRANSITION_DIVISIONS_DATA = "GET_TRANSITION_DIVISIONS_DATA";
export const GET_TRANSITION_DIVISIONS_START = "GET_TRANSITION_DIVISIONS_START";
export const GET_TRANSITION_DIVISIONS_DATA_SINGLE = "GET_TRANSITION_DIVISIONS_DATA_SINGLE";
export const GET_TRANSITION_DIVISIONS_END = "GET_TRANSITION_DIVISIONS_END";

// HR OPERATIONS ===> EDUCATION_LEVEL
export const GET_TRANSITION_EDUCATION_LEVEL_DATA = "GET_TRANSITION_EDUCATION_LEVEL_DATA";
export const GET_TRANSITION_EDUCATION_LEVEL_START = "GET_TRANSITION_EDUCATION_LEVEL_START";
export const GET_TRANSITION_EDUCATION_LEVEL_DATA_SINGLE = "GET_TRANSITION_EDUCATION_LEVEL_DATA_SINGLE";
export const GET_TRANSITION_EDUCATION_LEVEL_END = "GET_TRANSITION_EDUCATION_LEVEL_END";

// HR OPERATIONS ===> EDUCATION_LEVEL
export const GET_TRANSITION_EDUCATION_DATA = "GET_TRANSITION_EDUCATION_DATA";
export const GET_TRANSITION_EDUCATION_START = "GET_TRANSITION_EDUCATION_START";
export const GET_TRANSITION_EDUCATION_DATA_SINGLE = "GET_TRANSITION_EDUCATION_DATA_SINGLE";
export const GET_TRANSITION_EDUCATION_END = "GET_TRANSITION_EDUCATION_END";

// HR OPERATIONS ===> EMPOYLEE CAT
export const GET_TRANSITION_EMPLOYEE_CAT_DATA = "GET_TRANSITION_EMPLOYEE_CAT_DATA";
export const GET_TRANSITION_EMPLOYEE_CAT_START = "GET_TRANSITION_EMPLOYEE_CAT_START";
export const GET_TRANSITION_EMPLOYEE_CAT_SINGLE = "GET_TRANSITION_EMPLOYEE_CAT_SINGLE";
export const GET_TRANSITION_EMPLOYEE_CAT_END = "GET_TRANSITION_EMPLOYEE_CAT_END";

// HR OPERATIONS ===> EMPOYLEE TYPE
export const GET_TRANSITION_EMPOYLEE_TYPE_DATA = "GET_TRANSITION_EMPOYLEE_TYPE_DATA";
export const GET_TRANSITION_EMPOYLEE_TYPE_START = "GET_TRANSITION_EMPOYLEE_TYPE_START";
export const GET_TRANSITION_EMPOYLEE_TYPE_SINGLE = "GET_TRANSITION_EMPOYLEE_TYPE_SINGLE";
export const GET_TRANSITION_EMPOYLEE_TYPE_END = "GET_TRANSITION_EMPOYLEE_TYPE_END";

// HR OPERATIONS ===> POSITION
export const GET_TRANSITION_POSITION_DATA = "GET_TRANSITION_POSITION_DATA";
export const GET_TRANSITION_POSITION_START = "GET_TRANSITION_POSITION_START";
export const GET_TRANSITION_POSITION_SINGLE = "GET_TRANSITION_POSITION_SINGLE";
export const GET_TRANSITION_POSITION_END = "GET_TRANSITION_POSITION_END";

// HR OPERATIONS ===> GRADES
export const GET_TRANSITION_GRADES_DATA = "GET_TRANSITION_GRADES_DATA";
export const GET_TRANSITION_GRADES_START = "GET_TRANSITION_GRADES_START";
export const GET_TRANSITION_GRADES_SINGLE = "GET_TRANSITION_GRADES_SINGLE";
export const GET_TRANSITION_GRADES_END = "GET_TRANSITION_GRADES_END";



// PAYROLL ALLOWANCE ===>
export const GET_ALLOWANCE_START = "GET_ALLOWANCE_START";
export const GET_ALLOWANCE_COMPLETE = "GET_ALLOWANCE_COMPLETE";
export const GET_ALLOWANCE_END = "GET_ALLOWANCE_END";

