
// HR OPERATIONS ===> FAMILY TYPES
export const GET_TRANSITION_FAMILY_DATA = "GET_TRANSITION_FAMILY_DATA";
export const GET_TRANSITION_FAMILY_START = "GET_TRANSITION_FAMILY_START";
export const GET_TRANSITION_FAMILY_DATA_SINGLE = "GET_TRANSITION_FAMILY_DATA_SINGLE";
export const GET_TRANSITION_FAMILY_END = "GET_TRANSITION_FAMILY_END";


// HR OPERATIONS ===> COST CENTER
export const GET_TRANSITION_COST_CENTRE_DATA = "GET_TRANSITION_COST_CENTRE_DATA";
export const GET_TRANSITION_COST_CENTRE_START = "GET_TRANSITION_COST_CENTRE_START";
export const GET_TRANSITION_COST_CENTRE_DATA_SINGLE = "GET_TRANSITION_COST_CENTRE_DATA_SINGLE";
export const GET_TRANSITION_COST_CENTRE_END = "GET_TRANSITION_COST_CENTRE_END";


// HR OPERATIONS ===> COUNTRY
export const GET_TRANSITION_COUNTRY_DATA = "GET_TRANSITION_COUNTRY_DATA";
export const GET_TRANSITION_COUNTRY_START = "GET_TRANSITION_COUNTRY_START";
export const GET_TRANSITION_COUNTRY_DATA_SINGLE = "GET_TRANSITION_COUNTRY_DATA_SINGLE";
export const GET_TRANSITION_COUNTRY_END = "GET_TRANSITION_COUNTRY_END";


// HR OPERATIONS ===> DEPARTMENT
export const GET_TRANSITION_DEPARTMENT_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DEPARTMENT_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DEPARTMENT_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DEPARTMENT_END = "GET_TRANSITION_DEPARTMENT_END";

// HR OPERATIONS ===> DESIGNATION
export const GET_TRANSITION_DESIGNATION_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DESIGNATION_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DESIGNATION_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DESIGNATION_END = "GET_TRANSITION_DEPARTMENT_END";


