
// HR OPERATIONS ===> FAMILY TYPES
export const GET_TRANSITION_FAMILY_DATA = "GET_TRANSITION_FAMILY_DATA";
export const GET_TRANSITION_FAMILY_START = "GET_TRANSITION_FAMILY_START";
export const GET_TRANSITION_FAMILY_DATA_SINGLE = "GET_TRANSITION_FAMILY_DATA_SINGLE";
export const GET_TRANSITION_FAMILY_END = "GET_TRANSITION_FAMILY_END";


// HR OPERATIONS ===> COST CENTER
export const GET_TRANSITION_COST_CENTRE_DATA = "GET_TRANSITION_COST_CENTRE_DATA";
export const GET_TRANSITION_COST_CENTRE_START = "GET_TRANSITION_COST_CENTRE_START";
export const GET_TRANSITION_COST_CENTRE_DATA_SINGLE = "GET_TRANSITION_COST_CENTRE_DATA_SINGLE";
export const GET_TRANSITION_COST_CENTRE_END = "GET_TRANSITION_COST_CENTRE_END";


// HR OPERATIONS ===> COUNTRY
export const GET_TRANSITION_COUNTRY_DATA = "GET_TRANSITION_COUNTRY_DATA";
export const GET_TRANSITION_COUNTRY_START = "GET_TRANSITION_COUNTRY_START";
export const GET_TRANSITION_COUNTRY_DATA_SINGLE = "GET_TRANSITION_COUNTRY_DATA_SINGLE";
export const GET_TRANSITION_COUNTRY_END = "GET_TRANSITION_COUNTRY_END";


// HR OPERATIONS ===> DEPARTMENT
export const GET_TRANSITION_DEPARTMENT_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DEPARTMENT_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DEPARTMENT_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DEPARTMENT_END = "GET_TRANSITION_DEPARTMENT_END";

// HR OPERATIONS ===> DESIGNATION
export const GET_TRANSITION_DESIGNATION_DATA = "GET_TRANSITION_DEPARTMENT_DATA";
export const GET_TRANSITION_DESIGNATION_START = "GET_TRANSITION_DEPARTMENT_START";
export const GET_TRANSITION_DESIGNATION_DATA_SINGLE = "GET_TRANSITION_DEPARTMENT_DATA_SINGLE";
export const GET_TRANSITION_DESIGNATION_END = "GET_TRANSITION_DEPARTMENT_END";

// HR OPERATIONS ===> BASE CITY
export const GET_TRANSITION_BASE_CITY_DATA = "GET_TRANSITION_BASE_CITY_DATA";
export const GET_TRANSITION_BASE_CITY_START = "GET_TRANSITION_BASE_CITY_START";
export const GET_TRANSITION_BASE_CITY_DATA_SINGLE = "GET_TRANSITION_BASE_CITY_DATA_SINGLE";
export const GET_TRANSITION_BASE_CITY_END = "GET_TRANSITION_BASE_CITY_END";

// HR OPERATIONS ===> DIVISIONS
export const GET_TRANSITION_DIVISIONS_DATA = "GET_TRANSITION_DIVISIONS_DATA";
export const GET_TRANSITION_DIVISIONS_START = "GET_TRANSITION_DIVISIONS_START";
export const GET_TRANSITION_DIVISIONS_DATA_SINGLE = "GET_TRANSITION_DIVISIONS_DATA_SINGLE";
export const GET_TRANSITION_DIVISIONS_END = "GET_TRANSITION_DIVISIONS_END";

// HR OPERATIONS ===> EDUCATION_LEVEL
export const GET_TRANSITION_EDUCATION_LEVEL_DATA = "GET_TRANSITION_EDUCATION_LEVEL_DATA";
export const GET_TRANSITION_EDUCATION_LEVEL_START = "GET_TRANSITION_EDUCATION_LEVEL_START";
export const GET_TRANSITION_EDUCATION_LEVEL_DATA_SINGLE = "GET_TRANSITION_EDUCATION_LEVEL_DATA_SINGLE";
export const GET_TRANSITION_EDUCATION_LEVEL_END = "GET_TRANSITION_EDUCATION_LEVEL_END";

// HR OPERATIONS ===> EDUCATION_LEVEL
export const GET_TRANSITION_EDUCATION_DATA = "GET_TRANSITION_EDUCATION_DATA";
export const GET_TRANSITION_EDUCATION_START = "GET_TRANSITION_EDUCATION_START";
export const GET_TRANSITION_EDUCATION_DATA_SINGLE = "GET_TRANSITION_EDUCATION_DATA_SINGLE";
export const GET_TRANSITION_EDUCATION_END = "GET_TRANSITION_EDUCATION_END";

// HR OPERATIONS ===> EMPOYLEE CAT
export const GET_TRANSITION_EMPLOYEE_CAT_DATA = "GET_TRANSITION_EMPLOYEE_CAT_DATA";
export const GET_TRANSITION_EMPLOYEE_CAT_START = "GET_TRANSITION_EMPLOYEE_CAT_START";
export const GET_TRANSITION_EMPLOYEE_CAT_SINGLE = "GET_TRANSITION_EMPLOYEE_CAT_SINGLE";
export const GET_TRANSITION_EMPLOYEE_CAT_END = "GET_TRANSITION_EMPLOYEE_CAT_END";

// HR OPERATIONS ===> EMPOYLEE TYPE
export const GET_TRANSITION_EMPOYLEE_TYPE_DATA = "GET_TRANSITION_EMPOYLEE_TYPE_DATA";
export const GET_TRANSITION_EMPOYLEE_TYPE_START = "GET_TRANSITION_EMPOYLEE_TYPE_START";
export const GET_TRANSITION_EMPOYLEE_TYPE_SINGLE = "GET_TRANSITION_EMPOYLEE_TYPE_SINGLE";
export const GET_TRANSITION_EMPOYLEE_TYPE_END = "GET_TRANSITION_EMPOYLEE_TYPE_END";

// HR OPERATIONS ===> POSITION
export const GET_TRANSITION_POSITION_DATA = "GET_TRANSITION_POSITION_DATA";
export const GET_TRANSITION_POSITION_START = "GET_TRANSITION_POSITION_START";
export const GET_TRANSITION_POSITION_SINGLE = "GET_TRANSITION_POSITION_SINGLE";
export const GET_TRANSITION_POSITION_END = "GET_TRANSITION_POSITION_END";

// HR OPERATIONS ===> GRADES
export const GET_TRANSITION_GRADES_DATA = "GET_TRANSITION_GRADES_DATA";
export const GET_TRANSITION_GRADES_START = "GET_TRANSITION_GRADES_START";
export const GET_TRANSITION_GRADES_SINGLE = "GET_TRANSITION_GRADES_SINGLE";
export const GET_TRANSITION_GRADES_END = "GET_TRANSITION_GRADES_END";

// HR OPERATIONS ===> REFRESHABLE DATA 
export const GET_TRANSITION_REFRESHABLE_DATA = "GET_TRANSITION_REFRESHABLE_DATA";
export const GET_TRANSITION_REFRESHABLE_DATA_START = "GET_TRANSITION_REFRESHABLE_DATA_START";
export const GET_TRANSITION_REFRESHABLE_DATA_SINGLE = "GET_TRANSITION_REFRESHABLE_DATA_SINGLE";
export const GET_TRANSITION_REFRESHABLE_DATA_END = "GET_TRANSITION_REFRESHABLE_DATA_END";

// HR OPERATIONS ===> GRADES
export const GET_DOWNLOAD_PARA_ACCESS_DATA = "GET_DOWNLOAD_PARA_ACCESS_DATA";
export const GET_DOWNLOAD_PARA_ACCESS_START = "GET_DOWNLOAD_PARA_ACCESS_START";
export const GET_DOWNLOAD_PARA_ACCESS_SINGLE = "GET_DOWNLOAD_PARA_ACCESS_SINGLE";
export const GET_DOWNLOAD_PARA_ACCESS_END = "GET_DOWNLOAD_PARA_ACCESS_END";
export const GET_SELECT_USER_DATA = "GET_SELECT_USER_DATA"



// PAYROLL ALLOWANCE ===>
export const GET_ALLOWANCE_START = "GET_ALLOWANCE_START";
export const GET_ALLOWANCE_COMPLETE = "GET_ALLOWANCE_COMPLETE";
export const GET_ALLOWANCE_END = "GET_ALLOWANCE_END";


// HR OPERATIONS ===> MASTER PERSONAL
export const GET_MASTER_PERSONAL_DATA = "GET_MASTER_PERSONAL_DATA";
export const GET_MASTER_PERSONAL_START = "GET_MASTER_PERSONAL_START";
export const GET_MASTER_PERSONALSINGLE = "GET_MASTER_PERSONALSINGLE";
export const GET_MASTER_PERSONAL_END = "GET_MASTER_PERSONAL_END";
// // HR OPERATIONS ===> MasterPersonel 
// export const GET_TRANSITION_MASTERPERSONEL_DATA = "GET_TRANSITION_MASTERPERSONEL_DATA";
// export const GET_TRANSITION_MASTERPERSONEL_DATA_START = "GET_TRANSITION_MASTERPERSONEL_DATA_START";
// export const GET_TRANSITION_MASTERPERSONEL_DATA_SINGLE = "GET_TRANSITION_REFRESHABLE_DATA_SINGLE";
// export const GET_TRANSITION_MASTERPERSONEL_DATA_END = "GET_TRANSITION_MASTERPERSONEL_DATA_END";

// HR OPERATIONS ===> Instituion 

export const GET_TRANSITION_INSTITUTION_DATA = "GET_TRANSITION_INSTITUTION_DATA";
export const GET_TRANSITION_INSTITUTION_DATA_START = "GET_TRANSITION_INSTITUTION_DATA_START";
export const GET_TRANSITION_INSTITUTION_DATA_SINGLE = "GET_TRANSITION_INSTITUTION_DATA_SINGLE";
export const GET_TRANSITION_INSTITUTION_DATA_END = "GET_TRANSITION_INSTITUTION_DATA_END";

// HR OPERATIONS ===> Holidays 

export const GET_HOLIDAYS_DATA = "GET_HOLIDAYS_DATA";
export const GET_HOLIDAYS_DATA_START = "GET_HOLIDAYS_DATA_START";
export const GET_HOLIDAYS_DATA_SINGLE = "GET_HOLIDAYS_DATA_SINGLE";
export const GET_HOLIDAYS_DATA_END = "GET_HOLIDAYS_DATA_END";


// HR OPERATIONS ===> LOCATION 

export const GET_LOCATION_DATA = "GET_LOCATION_DATA";
export const GET_LOCATION_DATA_START = "GET_LOCATION_DATA_START";
export const GET_LOCATION_DATA_SINGLE = "GET_LOCATION_DATA_SINGLE";
export const GET_LOCATION_DATA_END = "GET_LOCATION_DATA_END";


// HR OPERATIONS ===> POSITION 

export const GET_POSITION_DATA = "GET_POSITION_DATA";
export const GET_POSITION_DATA_START = "GET_POSITION_DATA_START";
export const GET_POSITION_DATA_SINGLE = "GET_POSITION_DATA_SINGLE";
export const GET_POSITION_DATA_END = "GET_POSITION_DATA_END";

// MASTER MAINTAINCE ===> MASTER_EARNING 

export const GET_MASTER_EARNING_DATA = "GET_POSITION_DATA";
export const GET_MASTER_EARNING_DATA_START = "GET_POSITION_DATA_START";
export const GET_MASTER_EARNING_DATA_SINGLE = "GET_POSITION_DATA_SINGLE";
export const GET_MASTER_EARNING_DATA_END = "GET_POSITION_DATA_END";

// HR OPERATIONS ===> Leave_Category 

export const GET_TRANSITION_LEAVE_CATEGORY_DATA = "GET_TRANSITION_LEAVE_CATEGORY_DATA";
export const GET_TRANSITION_LEAVE_CATEGORY_DATA_START = "GET_TRANSITION_LEAVE_CATEGORY_DATA_START";
export const GET_TRANSITION_LEAVE_CATEGORY_DATA_SINGLE = "GET_TRANSITION_LEAVE_CATEGORY_DATA_SINGLE";
export const GET_TRANSITION_LEAVE_CATEGORY_DATA_END = "GET_TRANSITION_LEAVE_CATEGORY_DATA_END";

// HR OPERATIONS ===> Religion === 

export const GET_TRANSITION_RELIGION_DATA = "GET_TRANSITION_RELIGION_DATA";
export const GET_TRANSITION_RELIGION_DATA_START = "GET_TRANSITION_RELIGION_DATA_START";
export const GET_TRANSITION_RELIGION_DATA_SINGLE = "GET_TRANSITION_RELIGION_DATA_SINGLE";
export const GET_TRANSITION_RELIGION_DATA_END = "GET_TRANSITION_RELIGION_DATA_END";

// HR OPERATIONS ===> Resignation === 

export const GET_TRANSITION_RESIGNATION_DATA = "GET_TRANSITION_RESIGNATION_DATA";
export const GET_TRANSITION_RESIGNATION_DATA_START = "GET_TRANSITION_RESIGNTION_DATA_START";
export const GET_TRANSITION_RESIGNATION_DATA_SINGLE = "GET_TRANSITION_RESIGNATION_DATA_SINGLE";
export const GET_TRANSITION_RESIGNATION_DATA_END = "GET_TRANSITION_RESIGNATION_DATA_END";

// HR OPERATIONS ===> Section === 

export const GET_TRANSITION_SECTION_DATA = "GET_TRANSITION_SECTION_DATA";
export const GET_TRANSITION_SECTION_DATA_START = "GET_TRANSITION_SECTION_DATA_START";
export const GET_TRANSITION_SECTION_DATA_SINGLE = "GET_TRANSITION_SECTION_DATA_SINGLE";
export const GET_TRANSITION_SECTION_DATA_END = "GET_TRANSITION_SECTION_DATA_END";

// HR OPERATIONS ===> Previos Employer === 

export const GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA = "GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA";
export const GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_START = "GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_START";
export const GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_SINGLE = "GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_SINGLE";
export const GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_END = "GET_TRANSITION_PERVIOUS_EMPLOYEE_DATA_END";

// HR OPERATIONS ===> Leave Type === 
export const GET_TRANSITION_LEAVE_TYPE_DATA = "GET_TRANSITION_LEAVE_TYPE_DATA";
export const GET_TRANSITION_LEAVE_TYPE_DATA_START = "GET_TRANSITION_LEAVE_TYPE_DATA_START";
export const GET_TRANSITION_LEAVE_TYPE_DATA_SINGLE = "GET_TRANSITION_LEAVE_TYPE_DATA_SINGLE";
export const GET_TRANSITION_LEAVE_TYPE_DATA_END = "GET_TRANSITION_LEAVE_TYPE_DATA_END";

// MASTER MAINTAINCE ===> MASTER ACTIVE === 
export const GET_MASTER_ACTIVE_DATA = "GET_MASTER_ACTIVE_DATA";
export const GET_MASTER_ACTIVE_DATA_START = "GET_MASTER_ACTIVE_DATA_START";
export const GET_MASTER_ACTIVE_DATA_SINGLE = "GET_MASTER_ACTIVE_DATA_SINGLE";
export const GET_MASTER_ACTIVE_DATA_END = "GET_MASTER_ACTIVE_DATA_END";

// Appointment ===>Appointment  === 
export const GET_APPOINTMENT_DATA = "GET_APPOINTMENT_DATA";
export const GET_APPOINTMENT_DATA_START = "GET_APPOINTMENT_DATA_START";
export const GET_APPOINTMENT_DATA_SINGLE = "GET_APPOINTMENT_DATA_SINGLE";
export const GET_APPOINTMENT_DATA_END = "GET_APPOINTMENT_DATA_END";
